version: '3'

networks:
  elastic:
    external: true

services:
    kibana:
        image: docker.elastic.co/kibana/kibana:8.4.1
        container_name: kibana
        restart: always
        environment:
          SERVER_NAME: kibana
          ELASTICSEARCH_HOSTS: http://elasticsearch:9200
          ELASTICSEARCH_USERNAME: elastic
          ELASTICSEARCH_PASSWORD: linkgap
          # ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: /usr/share/kibana/certs/http_ca.crt
        ports:
          - "5601:5601"
        volumes:
          - ./kibana.yml:/usr/share/kibana/config/kibana.yml
          # - ./certs:/usr/share/kibana/certs
          - ./data:/usr/share/kibana/data
        networks:
          elastic:
        deploy:
          resources:
            limits:
              memory: 2G