version: '3'
services:
    portainter:
        image: portainer/portainer-ce:2.16.2
        container_name: portainer
        hostname: portainer
        restart: always
        privileged: true
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./date:/data"
        ports:
            - "9000:9000"
#            - "9443:9443"
