version: '3'

networks:
  elastic:
    external: true

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.1
    container_name: elasticsearch
    restart: always
    environment:
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: linkgap
    ports:
      - "9200:9200"
#      - "9300:9300"
    volumes:
      - ./esdata01:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
      - ./config:/usr/share/elasticsearch/config
    networks:
      elastic:
    deploy:
      resources:
        limits:
          memory: 2GB
    ulimits:
      memlock:
        soft: -1
        hard: -1
