version: '3'

networks:
    default:
      name: elastic
      external: true

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./esdata01:/usr/share/elasticsearch/data
      - ./config:/usr/share/elasticsearch/config
    environment:
      ELASTIC_USERNAME: elastic
      ELASTIC_PASSWORD: linkgap
    deploy:
      resources:
        limits:
          memory: 2GB
    ulimits:
      memlock:
        soft: -1
        hard: -1
