version: '3'
services:
  nacos:
    image: nacos/nacos-server:v2.1.2
    container_name: nacos-standalone-mysql
    hostname: nacos
    restart: always
    environment:
      MODE: standalone
      # 支持IP还是域名模式
      PREFER_HOST_MODE: hostname
#      NACOS_APPLICATION_PORT: 8848
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos_conf
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    volumes:
      - ./logs/:/home/nacos/logs
#      - ./conf/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      # web 端口
      - "8848:8848"
      # 客户端gRPC请求服务端端口 = web 端口 + 1000，用于客户端向服务端发起连接和请求
      #- "9848:9848"
      # 服务端gRPC请求服务端端口 = web 端口 + 1001，用于服务间同步等
      #- "9555:9555"
    networks:
      yace:
networks:
  yace:
    external: true
