version: '3'
services:
  nacos:
    image: nacos/nacos-server:2.1.2
    container_name: nacos-standalone-mysql
    hostname: nacos
    restart: always
    environment:
      MODE: standalone
      # 支持IP还是域名模式
      PREFER_HOST_MODE: hostname
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos_conf
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    volumes:
      - ./logs/:/home/nacos/logs
#      - ./conf/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
#      - "9848:9848"
#      - "9555:9555"
    networks:
      yace:
networks:
  yace:
    external: true
