version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2022-11-26T22-43-32Z
    container_name: minio
    hostname: minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
